# Generated by Django 4.2.4 on 2023-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='room_images/')),
                ('capacity', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('des', models.CharField(max_length=200)),
            ],
        ),
    ]
