# Generated by Django 4.2.1 on 2023-08-16 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0009_alter_useraccount_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('general', 'General'), ('special', 'Special')], default='general', max_length=10, verbose_name='Room Type')),
                ('capacity', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=20, verbose_name='Capacity')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReservation', models.DateField(default=django.utils.timezone.now)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.useraccount')),
                ('roomno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.room')),
            ],
        ),
    ]
