# Generated by Django 4.2.1 on 2023-08-16 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0010_remove_useraccount_id_alter_useraccount_email'),
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestName', models.CharField(default='', max_length=25)),
                ('roomType', models.CharField(default='General', max_length=25)),
                ('capacity', models.CharField(default='Single', max_length=25)),
                ('bookingDate', models.DateField(default=django.utils.timezone.now)),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('roomNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rooms.room')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Accounts.useraccount')),
            ],
        ),
    ]
