# Generated by Django 4.2.4 on 2023-08-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='des',
            new_name='description',
        ),
    ]
