# Generated by Django 4.2.4 on 2023-08-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_des_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=10),
        ),
    ]
