# Generated by Django 4.2.1 on 2023-08-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_booking_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='capacity',
            field=models.CharField(default='Single', max_length=25),
        ),
    ]
