# Generated by Django 4.2.4 on 2023-08-04 09:38

import booking.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_rooomtype_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=booking.models.get_room_type_capacity),
            preserve_default=False,
        ),
    ]
