# Generated by Django 4.2.4 on 2023-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_roomtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='ideal_for',
            field=models.CharField(choices=[('Human', 'Human'), ('Monster', 'Monster'), ('Human&Monster', 'Human&Monster')], max_length=50),
        ),
    ]
