# Generated by Django 4.2.1 on 2023-05-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customUser',
        ),
    ]
