# Generated by Django 4.2.1 on 2023-08-03 14:19

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_remove_useraccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(upload_to=Accounts.models.user_profile_pic_path),
        ),
    ]
